# Generated by Django 4.1.6 on 2023-02-13 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniversityClasses',
            new_name='UniversityCampus',
        ),
    ]
